# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e15e7e9b2a30622cb039c2bd73956617471e1ed5bc76b29c9c80c81029ccf4bcbc4983c4ec1cf11d43206c267fa3acce739a3abe6f3f3540667fbb28ecf787d2

test:
  secret_key_base: abf478081a70e711ffb3f0f22221c0d646633209d9aa7a33ec32805d161fd6e54f84659f232e33d8bc11e2ee09537a98411ebc18cc456615ace0fdb6d8692d67

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
